// autenticacion
export const LOGOUT='LOGOUT'
export const LOGIN='LOGIN'
export const RELOGIN='RELOGIN'
export const LOGIN_EXITO='LOGIN_EXITO'
export const LOGIN_ERROR='LOGIN_ERROR'
export const AGREGAR_USUARIO='AGREGAR_USUARIO'
export const AGREGAR_USUARIO_EXITO='AGREGAR_USUARIO_EXITO'
export const AGREGAR_USUARIO_ERROR='AGREGAR_USUARIO_ERROR'
// articulo
export const AGREGAR_ARTICULO='AGREGAR_ARTICULO'
export const AGREGAR_ARTICULO_EXITO='AGREGAR_ARTICULO_EXITO'
export const AGREGAR_ARTICULO_ERROR='AGREGAR_ARTICULO_ERROR'
export const OBTENER_ARTICULOS='OBTENER_ARTICULOS'
export const OBTENER_ARTICULO='OBTENER_ARTICULO'
export const OBTENER_MIS_ARTICULOS='OBTENER_MIS_ARTICULOS'
export const OBTENER_IMAGEN='OBTENER_IMAGEN'
export const OBTENER_ARTICULOS_FINALIZAR = 'OBTENER_ARTICULOS_FINALIZAR'
export const DELETE_ARTICULO = 'DELETE_ARTICULO'
export const UPDATE_ARTICULO = 'UPDATE_ARTICULO'
//categoria
export const OBTENER_CATEGORIAS = 'OBTENER_CATEGORIAS'
export const SAVE_CATEGORIA = 'SAVE_CATEGORIA'
export const DELETE_CATEGORIA = 'DELETE_CATEGORIA'

//Likes
export const SAVE_LIKE='SAVE_LIKE'
export const SAVE_LIKE_OBJECT='SAVE_LIKE_OBJECT'
export const DELETE_LIKE='DELETE_LIKE'
export const DELETE_LIKE_OBJECT='DELETE_LIKE_OBJECT'

//COMENTARIO
export const SAVE_COMENTARIO = 'SAVE_COMENTARIO'
export const DELETE_COMENTARIO = 'DELETE_COMENTARIO'


//General
export const ALERT='ALERT'